/**
 * JavaScript/TypeScript Best Practices Detection System v2.0
 * Based on: ESLint Rules, React Best Practices, TypeScript Guidelines, Node.js Security
 * Updated: 2024 Standards (ES2024, React 18+, TypeScript 5+, Node.js 20+)
 * 
 * Categories:
 * - React: Hooks, state management, performance, Server Components
 * - Async: Promises, async/await, error handling
 * - TypeScript: Type safety, generics, strict mode
 * - Security: XSS, injection, authentication, secrets
 * - Performance: Bundle size, rendering, memory
 * - Best Practices: Code style, patterns, maintainability
 */

import type { CodeIssue, SecurityFinding } from '../../types/analysis';

export interface JSDetectionRule {
  id: string;
  name: string;
  description: string;
  category: 'security' | 'performance' | 'best-practice' | 'style' | 'react' | 'async' | 'typescript' | 'node';
  severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
  pattern: RegExp;
  message: string;
  suggestion: string;
  references: string[];
  autoFixable: boolean;
  typescriptOnly?: boolean;
  fix?: (code: string, match: RegExpMatchArray) => string;
}

// Comprehensive JavaScript/TypeScript Detection Rules - 2024 Standards
export const JS_RULES: JSDetectionRule[] = [
  // ============ REACT HOOKS RULES ============
  {
    id: 'JS-REACT001',
    name: 'useEffect Missing Cleanup',
    description: 'Detects useEffect with subscriptions but no cleanup',
    category: 'react',
    severity: 'high',
    pattern: /useEffect\s*\(\s*(?:async\s*)?\(\s*\)\s*=>\s*\{[^}]*(?:addEventListener|subscribe|setInterval|setTimeout)[^}]*\}\s*,/g,
    message: 'useEffect with subscriptions/timers should return a cleanup function.',
    suggestion: 'Return cleanup function: useEffect(() => { const sub = ...; return () => sub.unsubscribe(); }, [])',
    references: ['React Hooks', 'useEffect Cleanup'],
    autoFixable: false,
  },
  {
    id: 'JS-REACT002',
    name: 'useState with Object/Array',
    description: 'Detects useState with mutable initial state',
    category: 'react',
    severity: 'medium',
    pattern: /useState\s*\(\s*(?:\[\s*\]|\{\s*\})\s*\)/g,
    message: 'Consider if you need memo/callback or if reducer pattern is better.',
    suggestion: 'For complex state, consider useReducer. For derived state, use useMemo.',
    references: ['React State Management', 'useReducer'],
    autoFixable: false,
  },
  {
    id: 'JS-REACT003',
    name: 'Async in useEffect',
    description: 'Detects async function directly in useEffect',
    category: 'react',
    severity: 'high',
    pattern: /useEffect\s*\(\s*async\s*\(\s*\)\s*=>/g,
    message: 'useEffect cannot be async directly. It should return cleanup function, not Promise.',
    suggestion: 'Create async function inside: useEffect(() => { const fetchData = async () => { ... }; fetchData(); }, [])',
    references: ['React useEffect', 'Async in Effects'],
    autoFixable: false,
  },
  {
    id: 'JS-REACT004',
    name: 'Missing useCallback for Props',
    description: 'Detects inline functions in JSX that could cause re-renders',
    category: 'react',
    severity: 'low',
    pattern: /<\w+[^>]*on\w+\s*=\s*\{\s*\(\s*\)\s*=>\s*\w+\s*\([^)]*\)\s*\}/g,
    message: 'Inline functions in JSX create new references on every render.',
    suggestion: 'Wrap in useCallback: const handleClick = useCallback(() => { ... }, [deps]);',
    references: ['React Performance', 'useCallback'],
    autoFixable: false,
  },
  {
    id: 'JS-REACT005',
    name: 'useMemo Overuse',
    description: 'Detects useMemo for simple values',
    category: 'react',
    severity: 'info',
    pattern: /useMemo\s*\(\s*\(\s*\)\s*=>\s*[^{]*,\s*\[\s*\]\s*\)/g,
    message: 'useMemo with empty deps and simple computation may be unnecessary.',
    suggestion: 'Only use useMemo for expensive computations or referential equality.',
    references: ['React useMemo', 'Performance Optimization'],
    autoFixable: false,
  },
  {
    id: 'JS-REACT006',
    name: 'Missing Key in List',
    description: 'Detects map without key prop',
    category: 'react',
    severity: 'high',
    pattern: /\.map\s*\([^)]*\)\s*=>\s*<\w+(?![^>]*key\s*=)/g,
    message: 'List items must have unique key prop for efficient reconciliation.',
    suggestion: 'Add unique key: items.map(item => <Item key={item.id} ... />)',
    references: ['React Keys', 'Reconciliation'],
    autoFixable: false,
  },
  {
    id: 'JS-REACT007',
    name: 'Index as Key',
    description: 'Detects array index used as React key',
    category: 'react',
    severity: 'medium',
    pattern: /\.map\s*\(\s*\([^,)]*,\s*(\w+)\s*\)[^>]*key\s*=\s*\{\s*\1\s*\}/g,
    message: 'Using index as key can cause issues with reordering and state.',
    suggestion: 'Use unique identifiers from your data: key={item.id}',
    references: ['React Keys', 'Index as Key Anti-pattern'],
    autoFixable: false,
  },
  {
    id: 'JS-REACT008',
    name: 'useState Without Type',
    description: 'Detects useState without explicit type in TypeScript',
    category: 'react',
    severity: 'low',
    pattern: /useState\s*\(\s*(?:null|undefined)\s*\)(?!<)/g,
    message: 'useState with null/undefined should have explicit type annotation.',
    suggestion: 'Add type: useState<Type | null>(null)',
    references: ['TypeScript React', 'useState Typing'],
    autoFixable: false,
    typescriptOnly: true,
  },
  {
    id: 'JS-REACT009',
    name: 'useEffect Missing Dependency',
    description: 'Detects useEffect with empty deps using external values',
    category: 'react',
    severity: 'high',
    pattern: /useEffect\s*\(\s*\(\s*\)\s*=>\s*\{[^}]*(?:props\.|state\.|\w+\[)[^}]*\}\s*,\s*\[\s*\]\s*\)/g,
    message: 'useEffect uses external values but has empty dependency array.',
    suggestion: 'Add dependencies to array or use useRef for values that shouldn\'t trigger re-runs.',
    references: ['React useEffect', 'Dependency Array'],
    autoFixable: false,
  },
  {
    id: 'JS-REACT010',
    name: 'Context Without Memoization',
    description: 'Detects context value without useMemo',
    category: 'react',
    severity: 'medium',
    pattern: /<\w+Context\.Provider\s+value\s*=\s*\{\s*\{[^}]+\}\s*\}/g,
    message: 'Context value object created on every render causes all consumers to re-render.',
    suggestion: 'Wrap value in useMemo: value={useMemo(() => ({ ... }), [deps])}',
    references: ['React Context', 'Performance'],
    autoFixable: false,
  },
  {
    id: 'JS-REACT011',
    name: 'Server Component With useState',
    description: 'Detects client-only hooks in potentially Server Components',
    category: 'react',
    severity: 'medium',
    pattern: /(?<!['"]use client['"][^}]*)(useState|useEffect|useContext)\s*\(/g,
    message: 'Hooks only work in Client Components. Add "use client" directive if needed.',
    suggestion: 'Add "use client" at top of file for components using hooks.',
    references: ['React Server Components', 'Next.js 13+'],
    autoFixable: false,
  },
  {
    id: 'JS-REACT012',
    name: 'Prop Drilling',
    description: 'Detects excessive prop passing',
    category: 'react',
    severity: 'info',
    pattern: /function\s+\w+\s*\(\s*\{[^}]{100,}\}\s*\)/g,
    message: 'Component has many props. Consider using Context or composition.',
    suggestion: 'Use React Context, Zustand, or component composition to reduce prop drilling.',
    references: ['React Context', 'Component Composition'],
    autoFixable: false,
  },
  {
    id: 'JS-REACT013',
    name: 'forwardRef Without displayName',
    description: 'Detects forwardRef without displayName',
    category: 'react',
    severity: 'info',
    pattern: /forwardRef\s*\([^)]*\)(?!\.displayName)/g,
    message: 'forwardRef component should have displayName for debugging.',
    suggestion: 'Add displayName: Component.displayName = "ComponentName"',
    references: ['React forwardRef', 'DevTools'],
    autoFixable: false,
  },

  // ============ ASYNC/AWAIT RULES ============
  {
    id: 'JS-ASYNC001',
    name: 'Unhandled Promise Rejection',
    description: 'Detects async calls without error handling',
    category: 'async',
    severity: 'high',
    pattern: /(?:await\s+\w+\s*\([^)]*\)|\.then\s*\([^)]*\))(?!\s*\.catch|\s*\.finally|catch)/g,
    message: 'Async operation without error handling. Unhandled rejections crash the app.',
    suggestion: 'Add try-catch: try { await ... } catch (e) { handleError(e); }',
    references: ['Error Handling', 'Async/Await'],
    autoFixable: false,
  },
  {
    id: 'JS-ASYNC002',
    name: 'Promise in Loop',
    description: 'Detects sequential await in loop',
    category: 'async',
    severity: 'medium',
    pattern: /(?:for|while)\s*\([^)]*\)\s*\{[^}]*await\s+\w+/g,
    message: 'Sequential awaits in loop. Consider parallel execution if order doesn\'t matter.',
    suggestion: 'Use Promise.all: await Promise.all(items.map(item => fetchItem(item)))',
    references: ['Async Performance', 'Promise.all'],
    autoFixable: false,
  },
  {
    id: 'JS-ASYNC003',
    name: 'Floating Promise',
    description: 'Detects promise not being awaited or handled',
    category: 'async',
    severity: 'high',
    pattern: /(?<!await\s)(?<!return\s)\w+\s*\.\s*(?:then|catch|finally)\s*\(/g,
    message: 'Promise result not awaited. May cause unintended behavior.',
    suggestion: 'Either await the promise or return it. Don\'t ignore promise results.',
    references: ['Promise Best Practices', 'Async/Await'],
    autoFixable: false,
  },
  {
    id: 'JS-ASYNC004',
    name: 'Async Function Without Await',
    description: 'Detects async functions that don\'t use await',
    category: 'async',
    severity: 'low',
    pattern: /async\s+(?:function\s+\w+|(?:\([^)]*\)|\w+)\s*=>)\s*\{(?![^}]*await)/g,
    message: 'Async function without await. Unnecessary Promise wrapping.',
    suggestion: 'Remove async keyword if not using await, or add await.',
    references: ['Async Functions'],
    autoFixable: false,
  },
  {
    id: 'JS-ASYNC005',
    name: 'Promise Constructor Anti-pattern',
    description: 'Detects unnecessary Promise constructor',
    category: 'async',
    severity: 'medium',
    pattern: /new\s+Promise\s*\(\s*(?:async\s*)?\([^)]*\)\s*=>\s*\{[^}]*await/g,
    message: 'Unnecessary Promise constructor wrapping async operation.',
    suggestion: 'Return the promise directly or use async/await without new Promise.',
    references: ['Promise Anti-patterns'],
    autoFixable: false,
  },
  {
    id: 'JS-ASYNC006',
    name: 'Callback Hell',
    description: 'Detects deeply nested callbacks',
    category: 'async',
    severity: 'medium',
    pattern: /\.then\s*\([^)]*\)\s*\.then\s*\([^)]*\)\s*\.then/g,
    message: 'Deeply nested promise chains are hard to read.',
    suggestion: 'Use async/await for cleaner asynchronous code.',
    references: ['Async/Await', 'Callback Hell'],
    autoFixable: false,
  },

  // ============ TYPESCRIPT RULES ============
  {
    id: 'JS-TS001',
    name: 'any Type Usage',
    description: 'Detects explicit any type usage',
    category: 'typescript',
    severity: 'medium',
    pattern: /:\s*any\b|as\s+any\b/g,
    message: 'Using \'any\' defeats TypeScript\'s type safety.',
    suggestion: 'Use proper types, unknown, or generics. Create interfaces for complex types.',
    references: ['TypeScript Best Practices', 'Type Safety'],
    autoFixable: false,
    typescriptOnly: true,
  },
  {
    id: 'JS-TS002',
    name: 'Non-null Assertion',
    description: 'Detects non-null assertion operator overuse',
    category: 'typescript',
    severity: 'medium',
    pattern: /\w+!\./g,
    message: 'Non-null assertion (!) bypasses type checking and can cause runtime errors.',
    suggestion: 'Use optional chaining (?.) or proper null checks.',
    references: ['TypeScript Non-null Assertion', 'Type Safety'],
    autoFixable: false,
    typescriptOnly: true,
  },
  {
    id: 'JS-TS003',
    name: 'Type Assertion Instead of Guard',
    description: 'Detects type assertions where guards are preferred',
    category: 'typescript',
    severity: 'low',
    pattern: /as\s+\w+(?:<[^>]+>)?\s*(?!\))/g,
    message: 'Type assertion (as) doesn\'t provide runtime safety.',
    suggestion: 'Use type guards for runtime type checking: if (isType(value)) { ... }',
    references: ['TypeScript Type Guards', 'Type Narrowing'],
    autoFixable: false,
    typescriptOnly: true,
  },
  {
    id: 'JS-TS004',
    name: 'Missing Return Type',
    description: 'Detects functions without explicit return types',
    category: 'typescript',
    severity: 'info',
    pattern: /(?:function\s+\w+|const\s+\w+\s*=\s*(?:async\s*)?\([^)]*\))\s*(?:=>|\{)(?!\s*:\s*\w)/g,
    message: 'Consider adding explicit return type for better documentation and safety.',
    suggestion: 'Add return type: function getName(): string { ... }',
    references: ['TypeScript Functions', 'Type Annotations'],
    autoFixable: false,
    typescriptOnly: true,
  },
  {
    id: 'JS-TS005',
    name: 'Object Type Instead of Record',
    description: 'Detects object type that should be Record',
    category: 'typescript',
    severity: 'info',
    pattern: /:\s*\{\s*\[key:\s*string\]\s*:\s*\w+\s*\}/g,
    message: 'Use Record<K, V> type for index signatures.',
    suggestion: 'Replace with Record<string, ValueType>',
    references: ['TypeScript Utility Types'],
    autoFixable: false,
    typescriptOnly: true,
  },
  {
    id: 'JS-TS006',
    name: 'Enum Instead of Union',
    description: 'Detects enum that could be string union',
    category: 'typescript',
    severity: 'info',
    pattern: /enum\s+\w+\s*\{[^}]*=[^}]*\}/g,
    message: 'String enums can be replaced with union types for better tree-shaking.',
    suggestion: 'Use type MyType = "a" | "b" | "c" instead of enum.',
    references: ['TypeScript Enums vs Unions'],
    autoFixable: false,
    typescriptOnly: true,
  },
  {
    id: 'JS-TS007',
    name: 'Generic Without Constraint',
    description: 'Detects generic type without constraint',
    category: 'typescript',
    severity: 'low',
    pattern: /<T>(?!\s*extends)/g,
    message: 'Generic type without constraint may be too permissive.',
    suggestion: 'Add constraint: <T extends BaseType> for better type inference.',
    references: ['TypeScript Generics'],
    autoFixable: false,
    typescriptOnly: true,
  },

  // ============ SECURITY RULES ============
  {
    id: 'JS-SEC001',
    name: 'innerHTML XSS',
    description: 'Detects potential XSS through innerHTML',
    category: 'security',
    severity: 'critical',
    pattern: /\.innerHTML\s*=\s*(?!["'`]<)/g,
    message: 'Setting innerHTML with dynamic content can lead to XSS attacks.',
    suggestion: 'Use textContent for text, or sanitize HTML with DOMPurify.',
    references: ['OWASP XSS', 'CWE-79'],
    autoFixable: false,
  },
  {
    id: 'JS-SEC002',
    name: 'eval Usage',
    description: 'Detects eval() and similar dynamic execution',
    category: 'security',
    severity: 'critical',
    pattern: /\beval\s*\(|new\s+Function\s*\(/g,
    message: 'eval() and new Function() execute arbitrary code. Major security risk.',
    suggestion: 'Use JSON.parse for data parsing. Avoid dynamic code execution.',
    references: ['OWASP Injection', 'CWE-94'],
    autoFixable: false,
  },
  {
    id: 'JS-SEC003',
    name: 'Hardcoded Credentials',
    description: 'Detects hardcoded API keys and secrets',
    category: 'security',
    severity: 'critical',
    pattern: /(?:apiKey|apiSecret|secretKey|password|token|bearer|auth)\s*[:=]\s*["'`][A-Za-z0-9_-]{8,}["'`]/gi,
    message: 'Hardcoded credentials detected. Can be extracted from source code.',
    suggestion: 'Use environment variables: process.env.API_KEY',
    references: ['OWASP A02', 'CWE-798'],
    autoFixable: false,
  },
  {
    id: 'JS-SEC004',
    name: 'Insecure Cookie',
    description: 'Detects cookies without security flags',
    category: 'security',
    severity: 'high',
    pattern: /document\.cookie\s*=\s*(?![^;]*(?:httponly|secure|samesite))/gi,
    message: 'Cookies should have security flags (httpOnly, secure, sameSite).',
    suggestion: 'Set secure cookie flags: document.cookie = "key=val; Secure; HttpOnly; SameSite=Strict"',
    references: ['OWASP Cookie Security', 'CWE-614'],
    autoFixable: false,
  },
  {
    id: 'JS-SEC005',
    name: 'dangerouslySetInnerHTML',
    description: 'Detects React dangerouslySetInnerHTML',
    category: 'security',
    severity: 'high',
    pattern: /dangerouslySetInnerHTML\s*=\s*\{\s*\{\s*__html:/g,
    message: 'dangerouslySetInnerHTML can lead to XSS if not sanitized.',
    suggestion: 'Sanitize content with DOMPurify before using dangerouslySetInnerHTML.',
    references: ['React Security', 'XSS Prevention'],
    autoFixable: false,
  },
  {
    id: 'JS-SEC006',
    name: 'SQL Injection Risk',
    description: 'Detects string concatenation in SQL queries',
    category: 'security',
    severity: 'critical',
    pattern: /(?:query|execute)\s*\(\s*(?:`[^`]*\$\{|["'][^"']*\+)/g,
    message: 'Potential SQL injection. User input concatenated into query.',
    suggestion: 'Use parameterized queries: db.query("SELECT * FROM users WHERE id = $1", [userId])',
    references: ['SQL Injection', 'CWE-89'],
    autoFixable: false,
  },
  {
    id: 'JS-SEC007',
    name: 'Regex DoS',
    description: 'Detects potentially dangerous regex patterns',
    category: 'security',
    severity: 'medium',
    pattern: /new\s+RegExp\s*\([^)]*\+/g,
    message: 'Dynamic regex from user input can cause ReDoS attacks.',
    suggestion: 'Validate and escape user input before using in RegExp.',
    references: ['ReDoS', 'CWE-1333'],
    autoFixable: false,
  },
  {
    id: 'JS-SEC008',
    name: 'Open Redirect',
    description: 'Detects potential open redirect vulnerabilities',
    category: 'security',
    severity: 'high',
    pattern: /(?:window\.location|location\.href)\s*=\s*(?:req\.|params\.|query\.)/g,
    message: 'Open redirect vulnerability. Redirecting based on user input.',
    suggestion: 'Validate redirect URL against whitelist of allowed domains.',
    references: ['Open Redirect', 'CWE-601'],
    autoFixable: false,
  },
  {
    id: 'JS-SEC009',
    name: 'Prototype Pollution',
    description: 'Detects potential prototype pollution',
    category: 'security',
    severity: 'high',
    pattern: /Object\.assign\s*\([^)]*,\s*(?:req\.|params\.|body\.)/g,
    message: 'Potential prototype pollution through Object.assign with user data.',
    suggestion: 'Validate and sanitize user input. Use Object.create(null) for clean objects.',
    references: ['Prototype Pollution', 'CWE-1321'],
    autoFixable: false,
  },
  {
    id: 'JS-SEC010',
    name: 'JWT Without Verification',
    description: 'Detects JWT usage without proper verification',
    category: 'security',
    severity: 'critical',
    pattern: /jwt\.decode\s*\((?!.*verify)/g,
    message: 'JWT decoded without verification. Tokens can be tampered.',
    suggestion: 'Use jwt.verify() to validate token signature.',
    references: ['JWT Security', 'CWE-347'],
    autoFixable: false,
  },

  // ============ NODE.JS RULES ============
  {
    id: 'JS-NODE001',
    name: 'Path Traversal',
    description: 'Detects potential path traversal vulnerabilities',
    category: 'node',
    severity: 'critical',
    pattern: /(?:fs\.|path\.join)\s*\([^)]*(?:req\.|params\.|query\.)/g,
    message: 'Potential path traversal attack. User input in file path.',
    suggestion: 'Use path.basename() and validate against allowed directories.',
    references: ['Path Traversal', 'CWE-22'],
    autoFixable: false,
  },
  {
    id: 'JS-NODE002',
    name: 'Command Injection',
    description: 'Detects potential command injection',
    category: 'node',
    severity: 'critical',
    pattern: /(?:exec|spawn|execSync)\s*\([^)]*(?:\$\{|req\.|params\.)/g,
    message: 'Potential command injection. User input in shell command.',
    suggestion: 'Use spawn with args array instead of exec with string.',
    references: ['Command Injection', 'CWE-78'],
    autoFixable: false,
  },
  {
    id: 'JS-NODE003',
    name: 'Sync Operations in Async Context',
    description: 'Detects synchronous operations that block event loop',
    category: 'node',
    severity: 'medium',
    pattern: /(?:fs\.(?:readFileSync|writeFileSync|appendFileSync)|JSON\.parse\s*\(\s*fs\.readFileSync)/g,
    message: 'Synchronous file operations block the event loop.',
    suggestion: 'Use async versions: fs.promises.readFile or fs.readFile with callback.',
    references: ['Node.js Event Loop', 'Async I/O'],
    autoFixable: false,
  },
  {
    id: 'JS-NODE004',
    name: 'Missing Error Event Handler',
    description: 'Detects streams/emitters without error handler',
    category: 'node',
    severity: 'high',
    pattern: /(?:createReadStream|createWriteStream|on\s*\(\s*['"]data['"])(?![^}]*\.on\s*\(\s*['"]error['"])/g,
    message: 'Stream/EventEmitter without error handler will crash on error.',
    suggestion: 'Add error handler: stream.on("error", err => { ... })',
    references: ['Node.js Streams', 'Error Handling'],
    autoFixable: false,
  },
  {
    id: 'JS-NODE005',
    name: 'Sensitive Data in Logs',
    description: 'Detects logging of sensitive data',
    category: 'node',
    severity: 'high',
    pattern: /console\.(?:log|info|debug)\s*\([^)]*(?:password|token|secret|key|credential)/gi,
    message: 'Potentially logging sensitive data.',
    suggestion: 'Remove sensitive data from logs or mask it.',
    references: ['Logging Security', 'OWASP'],
    autoFixable: false,
  },

  // ============ BEST PRACTICE RULES ============
  {
    id: 'JS-BP001',
    name: 'Loose Equality',
    description: 'Detects == instead of ===',
    category: 'best-practice',
    severity: 'low',
    pattern: /[^!=]==[^=]/g,
    message: 'Use strict equality (===) to avoid type coercion issues.',
    suggestion: 'Replace == with === for type-safe comparison.',
    references: ['ESLint eqeqeq', 'JavaScript Equality'],
    autoFixable: true,
    fix: (code, match) => code.replace(match[0], match[0].replace('==', '===')),
  },
  {
    id: 'JS-BP002',
    name: 'var Declaration',
    description: 'Detects var usage instead of const/let',
    category: 'best-practice',
    severity: 'low',
    pattern: /\bvar\s+\w+/g,
    message: 'Use const (default) or let instead of var for better scoping.',
    suggestion: 'Replace var with const if not reassigned, let if reassigned.',
    references: ['ESLint no-var', 'JavaScript Variables'],
    autoFixable: true,
    fix: (code, match) => code.replace(match[0], match[0].replace('var', 'const')),
  },
  {
    id: 'JS-BP003',
    name: 'console.log in Code',
    description: 'Detects console statements',
    category: 'best-practice',
    severity: 'info',
    pattern: /console\.(?:log|debug|info)\s*\(/g,
    message: 'Console statements should be removed from production code.',
    suggestion: 'Use a logging library or remove debug statements.',
    references: ['ESLint no-console', 'Production Code'],
    autoFixable: false,
  },
  {
    id: 'JS-BP004',
    name: 'Empty Catch Block',
    description: 'Detects empty catch blocks',
    category: 'best-practice',
    severity: 'high',
    pattern: /catch\s*\([^)]*\)\s*\{\s*\}/g,
    message: 'Empty catch block silently swallows errors.',
    suggestion: 'Log errors or rethrow: catch (e) { console.error(e); throw e; }',
    references: ['ESLint no-empty', 'Error Handling'],
    autoFixable: false,
  },
  {
    id: 'JS-BP005',
    name: 'Magic Numbers',
    description: 'Detects unexplained numeric literals',
    category: 'style',
    severity: 'info',
    pattern: /(?<![.\d])\b(?!0|1|2|-1|10|100|1000|200|201|204|400|401|403|404|500)\d{2,}\b(?![.\d])/g,
    message: 'Magic numbers reduce code readability.',
    suggestion: 'Extract to named constant: const MAX_ITEMS = 50;',
    references: ['ESLint no-magic-numbers', 'Code Clarity'],
    autoFixable: false,
  },
  {
    id: 'JS-BP006',
    name: 'Nested Ternary',
    description: 'Detects nested ternary operators',
    category: 'style',
    severity: 'medium',
    pattern: /\?\s*[^:]+:\s*[^:]+\?\s*[^:]+:/g,
    message: 'Nested ternary operators reduce readability.',
    suggestion: 'Use if-else statements or extract to separate conditions.',
    references: ['Code Readability'],
    autoFixable: false,
  },
  {
    id: 'JS-BP007',
    name: 'Function Too Long',
    description: 'Detects functions with too many lines',
    category: 'best-practice',
    severity: 'medium',
    pattern: /(?:function\s+\w+|const\s+\w+\s*=\s*(?:async\s*)?\([^)]*\)\s*=>)\s*\{(?:[^{}]*|\{[^{}]*\}){50,}/g,
    message: 'Function is too long. Consider breaking into smaller functions.',
    suggestion: 'Extract logical parts into separate functions for better maintainability.',
    references: ['Clean Code', 'Single Responsibility'],
    autoFixable: false,
  },
  {
    id: 'JS-BP008',
    name: 'TODO in Code',
    description: 'Detects TODO comments',
    category: 'style',
    severity: 'info',
    pattern: /\/\/\s*TODO|\/\*\s*TODO/gi,
    message: 'TODO comment found. Track in issue tracker instead.',
    suggestion: 'Create an issue in your project tracker and remove the TODO.',
    references: ['Code Hygiene'],
    autoFixable: false,
  },

  // ============ PERFORMANCE RULES ============
  {
    id: 'JS-PERF001',
    name: 'Large Bundle Import',
    description: 'Detects imports that may bloat bundle size',
    category: 'performance',
    severity: 'medium',
    pattern: /import\s+\w+\s+from\s+['"](?:lodash|moment|date-fns)(?!\/)['"]/g,
    message: 'Importing entire library. Use tree-shakeable imports.',
    suggestion: 'Import specific functions: import { debounce } from \'lodash/debounce\'',
    references: ['Bundle Optimization', 'Tree Shaking'],
    autoFixable: false,
  },
  {
    id: 'JS-PERF002',
    name: 'Unnecessary Spread',
    description: 'Detects unnecessary spread operator',
    category: 'performance',
    severity: 'low',
    pattern: /\.\.\.\[\s*\.\.\.(?:\w+)\s*\]/g,
    message: 'Nested spread operators are inefficient.',
    suggestion: 'Use flat() or flatMap() instead of nested spreads.',
    references: ['JavaScript Performance', 'Spread Operator'],
    autoFixable: false,
  },
  {
    id: 'JS-PERF003',
    name: 'Synchronous LocalStorage',
    description: 'Detects synchronous localStorage operations in critical path',
    category: 'performance',
    severity: 'medium',
    pattern: /localStorage\.(?:getItem|setItem|removeItem)\s*\(/g,
    message: 'localStorage is synchronous and can block main thread.',
    suggestion: 'Consider using IndexedDB or debouncing localStorage operations.',
    references: ['Web Storage', 'Main Thread Performance'],
    autoFixable: false,
  },
  {
    id: 'JS-PERF004',
    name: 'Large Array Operations',
    description: 'Detects potentially expensive array operations',
    category: 'performance',
    severity: 'low',
    pattern: /\.(?:filter|map|reduce)\s*\([^)]*\)\s*\.(?:filter|map|reduce)/g,
    message: 'Multiple chained array operations create intermediate arrays.',
    suggestion: 'Combine operations or use reduce for better performance.',
    references: ['JavaScript Performance', 'Array Methods'],
    autoFixable: false,
  },
  {
    id: 'JS-PERF005',
    name: 'Event Handler in Render',
    description: 'Detects event handlers created in render',
    category: 'performance',
    severity: 'low',
    pattern: /on\w+\s*=\s*\{\s*\([^)]*\)\s*=>/g,
    message: 'Arrow function in JSX creates new function on each render.',
    suggestion: 'Define handler outside render or use useCallback.',
    references: ['React Performance', 'Event Handlers'],
    autoFixable: false,
  },
  {
    id: 'JS-PERF006',
    name: 'CSS-in-JS in Render',
    description: 'Detects style objects created in render',
    category: 'performance',
    severity: 'low',
    pattern: /style\s*=\s*\{\s*\{[^}]+\}\s*\}/g,
    message: 'Inline style object created on every render.',
    suggestion: 'Move style object outside component or use useMemo.',
    references: ['React Performance', 'CSS-in-JS'],
    autoFixable: false,
  },
  {
    id: 'JS-PERF007',
    name: 'Document Query in Loop',
    description: 'Detects DOM queries inside loops',
    category: 'performance',
    severity: 'medium',
    pattern: /(?:for|while)\s*\([^)]*\)\s*\{[^}]*document\.(?:querySelector|getElementById)/g,
    message: 'DOM query inside loop is inefficient.',
    suggestion: 'Cache DOM element before loop: const el = document.querySelector(...)',
    references: ['DOM Performance'],
    autoFixable: false,
  },
];

/**
 * Run JavaScript/TypeScript-specific detection
 */
export function runJSDetection(code: string, isTypeScript: boolean = false): { issues: CodeIssue[]; securityFindings: SecurityFinding[] } {
  const issues: CodeIssue[] = [];
  const securityFindings: SecurityFinding[] = [];

  for (const rule of JS_RULES) {
    // Skip TypeScript-only rules for JavaScript
    if (rule.typescriptOnly && !isTypeScript) {
      continue;
    }

    const regex = new RegExp(rule.pattern.source, rule.pattern.flags);
    let match;

    while ((match = regex.exec(code)) !== null) {
      const beforeMatch = code.substring(0, match.index);
      const lineNumber = beforeMatch.split('\n').length;
      const column = match.index - beforeMatch.lastIndexOf('\n');

      const issue: CodeIssue = {
        id: `${rule.id}-${lineNumber}-${column}`,
        ruleId: rule.id,
        title: rule.name,
        description: rule.message,
        severity: rule.severity === 'critical' ? 'error' : 
                 rule.severity === 'high' ? 'error' :
                 rule.severity === 'medium' ? 'warning' : 'info',
        location: {
          line: lineNumber,
          column,
          endLine: lineNumber,
          endColumn: column + match[0].length,
          file: 'input',
        },
        category: rule.category as CodeIssue['category'],
        suggestion: rule.suggestion,
        autoFixable: rule.autoFixable,
        references: rule.references,
        codeSnippet: match[0],
      };

      issues.push(issue);

      if (rule.category === 'security' || rule.category === 'node') {
        securityFindings.push({
          id: issue.id,
          type: rule.name,
          severity: rule.severity,
          vulnerability: rule.name,
          description: rule.message,
          location: { line: lineNumber, column, file: 'input' },
          cwe: rule.references.find(r => r.startsWith('CWE-')),
          owaspCategory: rule.references.find(r => r.includes('OWASP')),
          recommendation: rule.suggestion,
          references: rule.references,
        });
      }
    }
  }

  return { issues, securityFindings };
}
