/**
 * Kotlin Best Practices Detection System v2.0
 * Based on: Kotlin Official Style Guide, Android Best Practices, Jetpack Guidelines
 * Updated: 2024 Standards (Kotlin 2.0+, Compose 1.6+, Coroutines 1.8+)
 * 
 * Categories:
 * - Null Safety: Force unwrap, platform types, lateinit
 * - Coroutines: GlobalScope, exception handling, Flow lifecycle
 * - Android: Memory leaks, lifecycle, View Binding
 * - Jetpack Compose: State management, side effects, performance
 * - Architecture: MVVM, Clean Architecture, UseCase patterns
 * - Security: Hardcoded secrets, insecure storage, logging
 * - Performance: String operations, collections, bitmap handling
 */

import type { CodeIssue, SecurityFinding } from '../../types/analysis';

export interface KotlinDetectionRule {
  id: string;
  name: string;
  description: string;
  category: 'security' | 'performance' | 'best-practice' | 'style' | 'android' | 'coroutines' | 'null-safety' | 'compose' | 'architecture';
  severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
  pattern: RegExp;
  message: string;
  suggestion: string;
  references: string[];
  autoFixable: boolean;
  fix?: (code: string, match: RegExpMatchArray) => string;
}

// Comprehensive Kotlin Detection Rules - Official Best Practices 2024
export const KOTLIN_RULES: KotlinDetectionRule[] = [
  // ============ NULL SAFETY RULES ============
  {
    id: 'KT-NULL001',
    name: 'Force Unwrap (!!) Usage',
    description: 'Detects force unwrap operator usage',
    category: 'null-safety',
    severity: 'high',
    pattern: /\w+!!\./g,
    message: 'Avoid using force unwrap (!!) operator. It can cause NullPointerException at runtime.',
    suggestion: 'Use safe call (?.) with let, elvis operator (?:), or proper null checks instead.',
    references: ['Kotlin Null Safety', 'Android Null Safety Guidelines'],
    autoFixable: false,
  },
  {
    id: 'KT-NULL002',
    name: 'Platform Type Without Null Check',
    description: 'Detects potential platform type issues',
    category: 'null-safety',
    severity: 'medium',
    pattern: /val\s+\w+\s*=\s*(?:intent\.get|bundle\.get|getIntent\(\)\.get)/g,
    message: 'Platform types from Java APIs should be explicitly typed as nullable.',
    suggestion: 'Add explicit nullable type: val data: String? = intent.getStringExtra("key")',
    references: ['Kotlin Platform Types', 'Android Intent Best Practices'],
    autoFixable: false,
  },
  {
    id: 'KT-NULL003',
    name: 'lateinit Without isInitialized Check',
    description: 'Detects lateinit usage without proper initialization check',
    category: 'null-safety',
    severity: 'medium',
    pattern: /lateinit\s+var\s+(\w+)\s*:/g,
    message: 'lateinit properties should be checked with ::property.isInitialized before access.',
    suggestion: 'Use lazy initialization or check isInitialized: if (::property.isInitialized) { ... }',
    references: ['Kotlin lateinit', 'Android ViewModel Best Practices'],
    autoFixable: false,
  },
  {
    id: 'KT-NULL004',
    name: 'Unsafe Cast (as)',
    description: 'Detects unsafe type casts',
    category: 'null-safety',
    severity: 'medium',
    pattern: /as\s+(?![\?])\w+/g,
    message: 'Unsafe cast (as) can throw ClassCastException at runtime.',
    suggestion: 'Use safe cast (as?) with null check: val result = value as? Type',
    references: ['Kotlin Type Casts', 'Safe Casting'],
    autoFixable: false,
  },
  {
    id: 'KT-NULL005',
    name: 'Nullable Receiver Without Safe Call',
    description: 'Detects method calls on potentially null values',
    category: 'null-safety',
    severity: 'high',
    pattern: /(?:getOrNull|firstOrNull|lastOrNull|singleOrNull)\s*\(\s*\)\s*\./g,
    message: 'Calling methods on nullable results without safe call operator.',
    suggestion: 'Use safe call: list.firstOrNull()?.property or Elvis operator.',
    references: ['Kotlin Null Safety'],
    autoFixable: false,
  },

  // ============ COROUTINES RULES ============
  {
    id: 'KT-COR001',
    name: 'GlobalScope Usage',
    description: 'Detects GlobalScope usage',
    category: 'coroutines',
    severity: 'high',
    pattern: /GlobalScope\.(?:launch|async)/g,
    message: 'Avoid GlobalScope. It creates unmanaged coroutines that can leak resources.',
    suggestion: 'Use structured concurrency: viewModelScope, lifecycleScope, or custom CoroutineScope.',
    references: ['Kotlin Coroutines Best Practices', 'Android Coroutines'],
    autoFixable: false,
  },
  {
    id: 'KT-COR002',
    name: 'Dispatchers.Main Without Context',
    description: 'Detects potential main thread issues',
    category: 'coroutines',
    severity: 'medium',
    pattern: /withContext\s*\(\s*Dispatchers\.Main\s*\)\s*\{[^}]*(?:database|network|file|http)/gi,
    message: 'Avoid running I/O operations on Dispatchers.Main.',
    suggestion: 'Use Dispatchers.IO for I/O operations, Dispatchers.Default for CPU-intensive work.',
    references: ['Kotlin Dispatchers', 'Android Threading'],
    autoFixable: false,
  },
  {
    id: 'KT-COR003',
    name: 'Missing Exception Handling in Coroutine',
    description: 'Detects coroutines without exception handling',
    category: 'coroutines',
    severity: 'high',
    pattern: /(?:launch|async)\s*\{(?![^}]*(?:try|catch|CoroutineExceptionHandler))[^}]*\}/g,
    message: 'Coroutine lacks exception handling. Uncaught exceptions crash the app.',
    suggestion: 'Add try-catch block or use CoroutineExceptionHandler.',
    references: ['Kotlin Exception Handling', 'Android Coroutines Safety'],
    autoFixable: false,
  },
  {
    id: 'KT-COR004',
    name: 'runBlocking on Main Thread',
    description: 'Detects runBlocking which can cause ANR',
    category: 'coroutines',
    severity: 'critical',
    pattern: /runBlocking\s*\{/g,
    message: 'runBlocking on main thread blocks UI and causes ANR.',
    suggestion: 'Use suspend functions with proper coroutine scope instead of runBlocking.',
    references: ['Kotlin runBlocking', 'Android ANR Prevention'],
    autoFixable: false,
  },
  {
    id: 'KT-COR005',
    name: 'Flow Without Lifecycle',
    description: 'Detects Flow collection without lifecycle awareness',
    category: 'coroutines',
    severity: 'medium',
    pattern: /\.collect\s*\{(?![^}]*(?:repeatOnLifecycle|flowWithLifecycle))/g,
    message: 'Flow collection should be lifecycle-aware to prevent leaks.',
    suggestion: 'Use repeatOnLifecycle or flowWithLifecycle for UI layer Flow collection.',
    references: ['Android Flow Best Practices', 'Lifecycle-Aware Components'],
    autoFixable: false,
  },
  {
    id: 'KT-COR006',
    name: 'Async Without Await',
    description: 'Detects async blocks without awaiting result',
    category: 'coroutines',
    severity: 'medium',
    pattern: /async\s*\{[^}]*\}(?!\.await)/g,
    message: 'async block result not awaited. The result Deferred should be awaited.',
    suggestion: 'Either await the result or use launch if you don\'t need the result.',
    references: ['Kotlin async/await', 'Coroutines'],
    autoFixable: false,
  },
  {
    id: 'KT-COR007',
    name: 'SupervisorJob Missing',
    description: 'Detects coroutine scopes without SupervisorJob',
    category: 'coroutines',
    severity: 'medium',
    pattern: /CoroutineScope\s*\(\s*Dispatchers\.\w+\s*\)/g,
    message: 'CoroutineScope without SupervisorJob. Child failures will cancel all siblings.',
    suggestion: 'Use CoroutineScope(SupervisorJob() + Dispatchers.Main) for independent child jobs.',
    references: ['SupervisorJob', 'Coroutine Scope'],
    autoFixable: false,
  },
  {
    id: 'KT-COR008',
    name: 'Channel Without Closing',
    description: 'Detects Channel creation without proper closing',
    category: 'coroutines',
    severity: 'medium',
    pattern: /Channel\s*<[^>]+>\s*\(/g,
    message: 'Channels should be closed when no longer needed to prevent resource leaks.',
    suggestion: 'Use channel.close() in finally block or use produce { } builder.',
    references: ['Kotlin Channels', 'Resource Management'],
    autoFixable: false,
  },
  {
    id: 'KT-COR009',
    name: 'StateFlow Without Initial Value',
    description: 'Detects MutableStateFlow with potential null issues',
    category: 'coroutines',
    severity: 'low',
    pattern: /MutableStateFlow\s*<[^>]*>\s*\(\s*null\s*\)/g,
    message: 'StateFlow initialized with null. Consider using a sealed class for states.',
    suggestion: 'Use sealed class UiState { object Loading, data class Success, data class Error }',
    references: ['StateFlow', 'UiState Pattern'],
    autoFixable: false,
  },

  // ============ ANDROID SPECIFIC RULES ============
  {
    id: 'KT-AND001',
    name: 'findViewById Usage',
    description: 'Detects deprecated findViewById usage',
    category: 'android',
    severity: 'low',
    pattern: /findViewById\s*<\s*\w+\s*>\s*\(/g,
    message: 'findViewById is deprecated. Use View Binding or Jetpack Compose.',
    suggestion: 'Migrate to View Binding: binding.viewId or use Jetpack Compose.',
    references: ['Android View Binding', 'Jetpack Compose'],
    autoFixable: false,
  },
  {
    id: 'KT-AND002',
    name: 'Hardcoded Dimension',
    description: 'Detects hardcoded dp/sp values',
    category: 'android',
    severity: 'low',
    pattern: /(?:\d+)\.dp|\(\s*\d+\s*\)\.dp/g,
    message: 'Avoid hardcoded dimensions. Use dimension resources for consistency.',
    suggestion: 'Define dimensions in res/values/dimens.xml and reference them.',
    references: ['Android Resource Guidelines'],
    autoFixable: false,
  },
  {
    id: 'KT-AND003',
    name: 'Activity/Fragment Memory Leak',
    description: 'Detects potential memory leaks',
    category: 'android',
    severity: 'critical',
    pattern: /(?:companion\s+object|object\s+\w+)\s*\{[^}]*(?:context|activity|fragment|view)\s*[=:]/gi,
    message: 'Storing Context/Activity/Fragment/View in object/companion object causes memory leaks.',
    suggestion: 'Use WeakReference or pass context as method parameter.',
    references: ['Android Memory Leaks', 'Context Best Practices'],
    autoFixable: false,
  },
  {
    id: 'KT-AND004',
    name: 'Handler Memory Leak',
    description: 'Detects Handler without WeakReference',
    category: 'android',
    severity: 'high',
    pattern: /(?:Handler|Runnable)\s*\{/g,
    message: 'Handler with inner class can cause memory leaks.',
    suggestion: 'Use lifecycleScope.launch with delay() or WeakReference pattern.',
    references: ['Android Handler Leaks', 'Coroutines for Delayed Tasks'],
    autoFixable: false,
  },
  {
    id: 'KT-AND005',
    name: 'onDestroy Cleanup Missing',
    description: 'Detects missing cleanup in lifecycle methods',
    category: 'android',
    severity: 'medium',
    pattern: /override\s+fun\s+onCreate[^}]*(?:observer|listener|callback|disposable)[^}]*\}/gi,
    message: 'Resources registered in onCreate should be cleaned up in onDestroy.',
    suggestion: 'Remove observers/listeners in onDestroy or use lifecycle-aware components.',
    references: ['Android Lifecycle', 'Memory Management'],
    autoFixable: false,
  },
  {
    id: 'KT-AND006',
    name: 'Fragment ViewBinding Leak',
    description: 'Detects Fragment ViewBinding not cleared in onDestroyView',
    category: 'android',
    severity: 'high',
    pattern: /private\s+(?:lateinit\s+)?var\s+_?binding\s*:\s*\w+Binding(?!\s*=\s*null)/g,
    message: 'Fragment ViewBinding should be nullified in onDestroyView to prevent leaks.',
    suggestion: 'Set _binding = null in onDestroyView().',
    references: ['ViewBinding in Fragments', 'Memory Leaks'],
    autoFixable: false,
  },
  {
    id: 'KT-AND007',
    name: 'Hardcoded String',
    description: 'Detects hardcoded strings in UI',
    category: 'android',
    severity: 'low',
    pattern: /(?:text|hint|contentDescription)\s*=\s*"[^"]{3,}"/g,
    message: 'Hardcoded strings in UI. Use string resources for localization.',
    suggestion: 'Move strings to res/values/strings.xml and use @string/resource_name.',
    references: ['Android Localization', 'String Resources'],
    autoFixable: false,
  },
  {
    id: 'KT-AND008',
    name: 'Context Held in ViewModel',
    description: 'Detects Context reference in ViewModel',
    category: 'android',
    severity: 'critical',
    pattern: /class\s+\w*ViewModel[^{]*\{[^}]*(?:private\s+)?(?:val|var)\s+\w*[Cc]ontext/g,
    message: 'ViewModel should not hold Context reference. Causes memory leaks.',
    suggestion: 'Use AndroidViewModel for Application context, or inject resources.',
    references: ['ViewModel', 'Memory Management'],
    autoFixable: false,
  },
  {
    id: 'KT-AND009',
    name: 'SharedPreferences on Main Thread',
    description: 'Detects blocking SharedPreferences operations',
    category: 'android',
    severity: 'medium',
    pattern: /getSharedPreferences[^}]*\.(?:getString|getInt|getBoolean|edit\(\)\.(?:putString|putInt|commit))/g,
    message: 'SharedPreferences operations are synchronous and may block main thread.',
    suggestion: 'Use DataStore or commit() in background thread, or apply() instead of commit().',
    references: ['DataStore', 'SharedPreferences'],
    autoFixable: false,
  },

  // ============ JETPACK COMPOSE RULES ============
  {
    id: 'KT-COMP001',
    name: 'State in Composable Parameter',
    description: 'Detects state hoisting issues',
    category: 'compose',
    severity: 'medium',
    pattern: /@Composable\s+fun\s+\w+\s*\([^)]*MutableState/g,
    message: 'Pass state value and callback instead of MutableState.',
    suggestion: 'Hoist state: fun MyComposable(value: T, onValueChange: (T) -> Unit)',
    references: ['Jetpack Compose State', 'State Hoisting'],
    autoFixable: false,
  },
  {
    id: 'KT-COMP002',
    name: 'remember Without Key',
    description: 'Detects remember without proper keys',
    category: 'compose',
    severity: 'low',
    pattern: /remember\s*\{[^}]*\}(?!\s*,)/g,
    message: 'Consider adding keys to remember for proper recomposition.',
    suggestion: 'Use remember(key1, key2) { } when the computation depends on values.',
    references: ['Compose remember', 'Recomposition'],
    autoFixable: false,
  },
  {
    id: 'KT-COMP003',
    name: 'Side Effect Without Key',
    description: 'Detects LaunchedEffect/DisposableEffect without keys',
    category: 'compose',
    severity: 'high',
    pattern: /(?:LaunchedEffect|DisposableEffect)\s*\(\s*(?:Unit|true)\s*\)/g,
    message: 'LaunchedEffect/DisposableEffect with Unit runs only once. Ensure this is intended.',
    suggestion: 'Use appropriate keys if the effect should re-run on data changes.',
    references: ['Compose Side Effects', 'LaunchedEffect Best Practices'],
    autoFixable: false,
  },
  {
    id: 'KT-COMP004',
    name: 'Heavy Computation in Composition',
    description: 'Detects expensive operations in composables',
    category: 'performance',
    severity: 'high',
    pattern: /@Composable\s+fun[^{]*\{[^}]*(?:\.map\s*\{|\.filter\s*\{|\.sortedBy|\.groupBy)/g,
    message: 'Collection operations in composables run on every recomposition.',
    suggestion: 'Use remember { list.map { ... } } or derivedStateOf for computed values.',
    references: ['Compose Performance', 'derivedStateOf'],
    autoFixable: false,
  },
  {
    id: 'KT-COMP005',
    name: 'Unstable Parameters',
    description: 'Detects parameters that prevent recomposition skipping',
    category: 'performance',
    severity: 'medium',
    pattern: /@Composable\s+fun\s+\w+\s*\([^)]*(?:List<|Map<|Set<|Array<)(?!@Stable|@Immutable)/g,
    message: 'Collection parameters are unstable and prevent recomposition skipping.',
    suggestion: 'Use @Stable/@Immutable annotations or kotlinx.collections.immutable.',
    references: ['Compose Stability', 'Performance Optimization'],
    autoFixable: false,
  },
  {
    id: 'KT-COMP006',
    name: 'Mutable State Without Remember',
    description: 'Detects mutableStateOf without remember',
    category: 'compose',
    severity: 'high',
    pattern: /(?<!remember\s*\{[^}]*)mutableStateOf\s*\(/g,
    message: 'mutableStateOf outside remember will reset on every recomposition.',
    suggestion: 'Wrap with remember { mutableStateOf(...) } or move state to ViewModel.',
    references: ['Compose State', 'remember'],
    autoFixable: false,
  },
  {
    id: 'KT-COMP007',
    name: 'State Not Survived Configuration Change',
    description: 'Detects state that won\'t survive configuration changes',
    category: 'compose',
    severity: 'medium',
    pattern: /remember\s*\{\s*mutableStateOf(?!.*rememberSaveable)/g,
    message: 'State in remember will be lost on configuration changes (rotation).',
    suggestion: 'Use rememberSaveable for UI state that should survive config changes, or hoist to ViewModel.',
    references: ['rememberSaveable', 'Configuration Changes', 'ViewModel'],
    autoFixable: false,
  },
  {
    id: 'KT-COMP008',
    name: 'derivedStateOf Misuse',
    description: 'Detects potential derivedStateOf misuse',
    category: 'performance',
    severity: 'medium',
    pattern: /derivedStateOf\s*\{[^}]*(?:fetch|load|api|network|database)/gi,
    message: 'derivedStateOf should derive from other State objects, not perform I/O.',
    suggestion: 'Use LaunchedEffect for async operations, derivedStateOf for computed values.',
    references: ['derivedStateOf', 'Compose Side Effects'],
    autoFixable: false,
  },
  {
    id: 'KT-COMP009',
    name: 'Composable Returning Non-Unit',
    description: 'Detects Composable functions with return values',
    category: 'compose',
    severity: 'medium',
    pattern: /@Composable\s+fun\s+\w+\s*\([^)]*\)\s*:\s*(?!Unit)/g,
    message: 'Composable functions should typically return Unit.',
    suggestion: 'Use state hoisting instead of returning values from Composables.',
    references: ['Compose Guidelines', 'State Hoisting'],
    autoFixable: false,
  },
  {
    id: 'KT-COMP010',
    name: 'SideEffect Instead of LaunchedEffect',
    description: 'Detects SideEffect for async operations',
    category: 'compose',
    severity: 'medium',
    pattern: /SideEffect\s*\{[^}]*(?:suspend|await|coroutine|async|launch)/gi,
    message: 'SideEffect runs on every recomposition. Use LaunchedEffect for async work.',
    suggestion: 'Use LaunchedEffect(key) { } for async operations.',
    references: ['SideEffect', 'LaunchedEffect'],
    autoFixable: false,
  },

  // ============ ARCHITECTURE RULES ============
  {
    id: 'KT-ARCH001',
    name: 'ViewModel Accessing Android Context',
    description: 'Detects ViewModel holding Context reference',
    category: 'architecture',
    severity: 'critical',
    pattern: /class\s+\w+ViewModel[^{]*\{[^}]*(?:Context|Activity|Fragment)(?![^}]*(?:Application|AndroidViewModel))/gi,
    message: 'ViewModel should not hold references to Context, Activity, or Fragment.',
    suggestion: 'Use AndroidViewModel for Application context, or pass context through use case parameters.',
    references: ['Android ViewModel', 'Memory Leaks', 'Clean Architecture'],
    autoFixable: false,
  },
  {
    id: 'KT-ARCH002',
    name: 'Repository in Activity/Fragment',
    description: 'Detects direct repository access in UI layer',
    category: 'architecture',
    severity: 'high',
    pattern: /class\s+\w+(?:Activity|Fragment)[^{]*\{[^}]*(?:Repository|DataSource|Dao)\s*[=:]/gi,
    message: 'UI layer should not access Repository directly. Violates MVVM/Clean Architecture.',
    suggestion: 'Access data through ViewModel. ViewModel should use UseCases or Repository.',
    references: ['Clean Architecture', 'MVVM Pattern', 'Android Architecture'],
    autoFixable: false,
  },
  {
    id: 'KT-ARCH003',
    name: 'Business Logic in Composable',
    description: 'Detects business logic inside Composable functions',
    category: 'architecture',
    severity: 'medium',
    pattern: /@Composable\s+fun[^{]*\{[^}]*(?:Repository|UseCase|DataSource|Api\w+|Retrofit)/gi,
    message: 'Composable functions should not contain business logic or data access.',
    suggestion: 'Move business logic to ViewModel. Composables should only render UI.',
    references: ['Jetpack Compose', 'MVVM', 'Separation of Concerns'],
    autoFixable: false,
  },
  {
    id: 'KT-ARCH004',
    name: 'Missing UseCase Layer',
    description: 'Detects ViewModel directly using Repository',
    category: 'architecture',
    severity: 'low',
    pattern: /class\s+\w+ViewModel[^{]*(?:@Inject[^{]*)?constructor\s*\([^)]*Repository[^)]*\)/gi,
    message: 'Consider using UseCase/Interactor layer between ViewModel and Repository.',
    suggestion: 'Create UseCase classes for business logic. Helps with testability and single responsibility.',
    references: ['Clean Architecture', 'UseCase Pattern', 'Android Architecture'],
    autoFixable: false,
  },
  {
    id: 'KT-ARCH005',
    name: 'Network Call in ViewModel Init',
    description: 'Detects network calls in ViewModel init block',
    category: 'architecture',
    severity: 'medium',
    pattern: /class\s+\w*ViewModel[^}]*init\s*\{[^}]*(?:fetch|load|api|network|http)/gi,
    message: 'Network calls in init block can cause issues with testing and lifecycle.',
    suggestion: 'Expose a load() function and call it from UI when ready.',
    references: ['ViewModel Best Practices', 'Testability'],
    autoFixable: false,
  },
  {
    id: 'KT-ARCH006',
    name: 'UI Logic in ViewModel',
    description: 'Detects UI-specific logic in ViewModel',
    category: 'architecture',
    severity: 'medium',
    pattern: /class\s+\w*ViewModel[^}]*(?:Toast|Snackbar|Dialog|Navigation|navigate)/gi,
    message: 'ViewModel should not contain UI-specific logic (Toast, Navigation).',
    suggestion: 'Use SingleLiveEvent, Channels, or state-based navigation.',
    references: ['ViewModel', 'Clean Architecture'],
    autoFixable: false,
  },

  // ============ BEST PRACTICE RULES ============
  {
    id: 'KT-BP001',
    name: 'Mutable Collection Exposure',
    description: 'Detects public mutable collection exposure',
    category: 'best-practice',
    severity: 'medium',
    pattern: /(?:val|var)\s+\w+\s*:\s*Mutable(?:List|Map|Set)</g,
    message: 'Avoid exposing mutable collections publicly.',
    suggestion: 'Expose as immutable (List, Map, Set) and use private mutable backing field.',
    references: ['Kotlin Collections', 'Encapsulation'],
    autoFixable: false,
  },
  {
    id: 'KT-BP002',
    name: 'Data Class with var Properties',
    description: 'Detects data classes with mutable properties',
    category: 'best-practice',
    severity: 'low',
    pattern: /data\s+class\s+\w+\s*\([^)]*\bvar\b/g,
    message: 'Data classes should use val (immutable) properties.',
    suggestion: 'Use val instead of var. Create new instances using copy() for modifications.',
    references: ['Kotlin Data Classes', 'Immutability'],
    autoFixable: true,
    fix: (code, _match) => code.replace(/data\s+class\s+(\w+)\s*\(([^)]*)\bvar\b/, 'data class $1($2val'),
  },
  {
    id: 'KT-BP003',
    name: 'Empty Catch Block',
    description: 'Detects empty catch blocks',
    category: 'best-practice',
    severity: 'high',
    pattern: /catch\s*\([^)]+\)\s*\{\s*\}/g,
    message: 'Empty catch block silently swallows exceptions.',
    suggestion: 'Log the exception or rethrow. Never silently ignore errors.',
    references: ['Exception Handling', 'Error Logging'],
    autoFixable: false,
  },
  {
    id: 'KT-BP004',
    name: 'apply/also Misuse',
    description: 'Detects incorrect scope function usage',
    category: 'style',
    severity: 'info',
    pattern: /\.apply\s*\{[^}]*return@apply/g,
    message: 'apply should configure object, not return values. Use let or run instead.',
    suggestion: 'Use apply for object configuration, let for transformations, also for side effects.',
    references: ['Kotlin Scope Functions'],
    autoFixable: false,
  },
  {
    id: 'KT-BP005',
    name: 'Redundant Null Check',
    description: 'Detects redundant null checks',
    category: 'style',
    severity: 'info',
    pattern: /(\w+)\s*!=\s*null\s*&&\s*\1\./g,
    message: 'Redundant null check. Use safe call operator instead.',
    suggestion: 'Replace: if (x != null && x.y) with x?.y',
    references: ['Kotlin Null Safety'],
    autoFixable: true,
    fix: (code, match) => {
      const varName = match[1];
      return code.replace(new RegExp(`${varName}\\s*!=\\s*null\\s*&&\\s*${varName}\\.`, 'g'), `${varName}?.`);
    },
  },
  {
    id: 'KT-BP006',
    name: 'Object Expression Instead of Lambda',
    description: 'Detects object expressions that could be lambdas',
    category: 'style',
    severity: 'info',
    pattern: /object\s*:\s*\w+\s*\{[^}]*override\s+fun\s+\w+\s*\([^)]*\)/g,
    message: 'Single-method object expression can be replaced with lambda (SAM conversion).',
    suggestion: 'Use lambda: setOnClickListener { handleClick() }',
    references: ['SAM Conversions', 'Kotlin Lambda'],
    autoFixable: false,
  },

  // ============ SECURITY RULES ============
  {
    id: 'KT-SEC001',
    name: 'Hardcoded Secret',
    description: 'Detects hardcoded secrets in Kotlin code',
    category: 'security',
    severity: 'critical',
    pattern: /(?:apiKey|secretKey|password|token|credential)\s*=\s*"[^"]{8,}"/gi,
    message: 'Hardcoded secret detected. Store secrets securely.',
    suggestion: 'Use Android Keystore, encrypted SharedPreferences, or environment variables.',
    references: ['Android Security Best Practices', 'OWASP Mobile'],
    autoFixable: false,
  },
  {
    id: 'KT-SEC002',
    name: 'Insecure SharedPreferences',
    description: 'Detects unencrypted SharedPreferences for sensitive data',
    category: 'security',
    severity: 'high',
    pattern: /getSharedPreferences\s*\([^)]*\)(?:[^}]*(?:token|password|key|secret|credential))/gi,
    message: 'Storing sensitive data in unencrypted SharedPreferences.',
    suggestion: 'Use EncryptedSharedPreferences from AndroidX Security library.',
    references: ['Android Security', 'EncryptedSharedPreferences'],
    autoFixable: false,
  },
  {
    id: 'KT-SEC003',
    name: 'WebView JavaScript Enabled',
    description: 'Detects potentially insecure WebView configuration',
    category: 'security',
    severity: 'medium',
    pattern: /settings\.javaScriptEnabled\s*=\s*true/g,
    message: 'WebView with JavaScript enabled can be vulnerable to XSS.',
    suggestion: 'Only enable JavaScript if necessary. Implement proper input validation.',
    references: ['Android WebView Security', 'OWASP Mobile'],
    autoFixable: false,
  },
  {
    id: 'KT-SEC004',
    name: 'Logging Sensitive Data',
    description: 'Detects logging of potentially sensitive data',
    category: 'security',
    severity: 'high',
    pattern: /Log\.(?:d|e|i|v|w)\s*\([^)]*(?:password|token|secret|key|credential|ssn|credit)/gi,
    message: 'Sensitive data may be logged. Logs can be accessed on rooted devices.',
    suggestion: 'Remove sensitive data from logs. Use ProGuard/R8 to strip logs in release builds.',
    references: ['Android Logging Best Practices', 'Security Logging'],
    autoFixable: false,
  },
  {
    id: 'KT-SEC005',
    name: 'SQL Injection Risk',
    description: 'Detects potential SQL injection in Room/SQLite',
    category: 'security',
    severity: 'critical',
    pattern: /(?:rawQuery|execSQL)\s*\(\s*(?:"[^"]*\$|"[^"]*\+)/g,
    message: 'Potential SQL injection. User input is concatenated into SQL query.',
    suggestion: 'Use parameterized queries or Room @Query with parameters.',
    references: ['Android SQL Injection', 'Room Database'],
    autoFixable: false,
  },
  {
    id: 'KT-SEC006',
    name: 'Hardcoded String - Password',
    description: 'Detects hardcoded passwords',
    category: 'security',
    severity: 'critical',
    pattern: /(?:password|passwd|pwd)\s*=\s*"[^"]+"/gi,
    message: 'CRITICAL: Hardcoded password detected. This is a severe security vulnerability.',
    suggestion: 'Never hardcode passwords. Use EncryptedSharedPreferences or Android Keystore.',
    references: ['OWASP Mobile Top 10', 'CWE-259', 'Android Security'],
    autoFixable: false,
  },
  {
    id: 'KT-SEC007',
    name: 'Hardcoded String - Firebase/Database URL',
    description: 'Detects hardcoded database URLs',
    category: 'security',
    severity: 'critical',
    pattern: /(?:firebase|database|mongo|mysql|postgres)[A-Za-z]*(?:Url|URI)\s*=\s*"[^"]+"/gi,
    message: 'CRITICAL: Hardcoded database URL detected. Database credentials exposed.',
    suggestion: 'Use BuildConfig fields or secure remote configuration.',
    references: ['OWASP Mobile Top 10', 'CWE-798', 'Android BuildConfig'],
    autoFixable: false,
  },
  {
    id: 'KT-SEC008',
    name: 'Hardcoded String - Bearer Token',
    description: 'Detects hardcoded bearer tokens',
    category: 'security',
    severity: 'critical',
    pattern: /(?:bearer|authorization)\s*=\s*"[^"]{10,}"/gi,
    message: 'CRITICAL: Hardcoded authorization token detected. Token can be extracted from APK.',
    suggestion: 'Fetch tokens dynamically from secure backend. Never store in code.',
    references: ['OWASP Mobile Top 10', 'CWE-798'],
    autoFixable: false,
  },
  {
    id: 'KT-SEC009',
    name: 'Hardcoded String - Private Key',
    description: 'Detects hardcoded private keys',
    category: 'security',
    severity: 'critical',
    pattern: /(?:privateKey|private_key|-----BEGIN\s+(?:RSA\s+)?PRIVATE\s+KEY-----)/gi,
    message: 'CRITICAL: Private key detected in code. Immediate security risk.',
    suggestion: 'Store private keys in Android Keystore. Never commit to source control.',
    references: ['OWASP Mobile Top 10', 'CWE-321', 'Android Keystore'],
    autoFixable: false,
  },
  {
    id: 'KT-SEC010',
    name: 'Hardcoded String - AWS/Cloud Credentials',
    description: 'Detects hardcoded cloud credentials',
    category: 'security',
    severity: 'critical',
    pattern: /(?:aws_access_key|aws_secret|AKIA[A-Z0-9]{16})/gi,
    message: 'CRITICAL: Cloud credentials detected in code. These can be used to compromise cloud resources.',
    suggestion: 'Use AWS Cognito or similar service for secure credential management.',
    references: ['OWASP Mobile Top 10', 'CWE-798', 'AWS Security'],
    autoFixable: false,
  },
  {
    id: 'KT-SEC011',
    name: 'Certificate Pinning Missing',
    description: 'Detects OkHttp without certificate pinning',
    category: 'security',
    severity: 'medium',
    pattern: /OkHttpClient\s*(?:\(\)|\.Builder\s*\(\))(?![^}]*certificatePinner)/g,
    message: 'OkHttpClient without certificate pinning. Vulnerable to MITM attacks.',
    suggestion: 'Implement certificate pinning: .certificatePinner(CertificatePinner.Builder()...)',
    references: ['Certificate Pinning', 'OWASP Mobile'],
    autoFixable: false,
  },

  // ============ PERFORMANCE RULES ============
  {
    id: 'KT-PERF001',
    name: 'String Concatenation in Loop',
    description: 'Detects string concatenation in loops',
    category: 'performance',
    severity: 'medium',
    pattern: /(?:for|while)\s*\([^)]+\)\s*\{[^}]*\+=\s*"[^"]*"/g,
    message: 'String concatenation in loop is inefficient.',
    suggestion: 'Use StringBuilder or buildString { } for string construction in loops.',
    references: ['Kotlin StringBuilder', 'Performance'],
    autoFixable: false,
  },
  {
    id: 'KT-PERF002',
    name: 'Sequence vs Collection',
    description: 'Detects chained collection operations that should use Sequence',
    category: 'performance',
    severity: 'low',
    pattern: /\.\w+\s*\{[^}]*\}\s*\.\w+\s*\{[^}]*\}\s*\.\w+\s*\{/g,
    message: 'Multiple chained collection operations. Consider using Sequence for large collections.',
    suggestion: 'Use .asSequence() for 3+ chained operations on large collections.',
    references: ['Kotlin Sequences', 'Collection Performance'],
    autoFixable: false,
  },
  {
    id: 'KT-PERF003',
    name: 'Bitmap Without Recycling',
    description: 'Detects bitmap usage without proper memory management',
    category: 'performance',
    severity: 'high',
    pattern: /BitmapFactory\.decode(?!.*recycle)/g,
    message: 'Bitmap loaded without explicit memory management.',
    suggestion: 'Use Coil, Glide, or Picasso for image loading. They handle memory efficiently.',
    references: ['Android Image Loading', 'Memory Management'],
    autoFixable: false,
  },
  {
    id: 'KT-PERF004',
    name: 'Inefficient Regex Creation',
    description: 'Detects regex created inside loops',
    category: 'performance',
    severity: 'medium',
    pattern: /(?:for|while)\s*\([^)]+\)\s*\{[^}]*(?:Regex|toRegex)\s*\(/g,
    message: 'Regex compiled inside loop. This is inefficient.',
    suggestion: 'Compile regex outside the loop and reuse: val regex = "pattern".toRegex()',
    references: ['Regex Performance', 'Kotlin'],
    autoFixable: false,
  },
  {
    id: 'KT-PERF005',
    name: 'Boxing Overhead',
    description: 'Detects potential boxing overhead with primitives',
    category: 'performance',
    severity: 'low',
    pattern: /List<(?:Int|Long|Double|Float|Boolean)>/g,
    message: 'Using boxed primitives in collections. Consider specialized arrays for performance.',
    suggestion: 'Use IntArray, LongArray, etc. for primitive collections in performance-critical code.',
    references: ['Kotlin Arrays', 'Boxing'],
    autoFixable: false,
  },
];

/**
 * Run Kotlin-specific detection
 */
export function runKotlinDetection(code: string): { issues: CodeIssue[]; securityFindings: SecurityFinding[] } {
  const issues: CodeIssue[] = [];
  const securityFindings: SecurityFinding[] = [];

  for (const rule of KOTLIN_RULES) {
    const regex = new RegExp(rule.pattern.source, rule.pattern.flags);
    let match;

    while ((match = regex.exec(code)) !== null) {
      const beforeMatch = code.substring(0, match.index);
      const lineNumber = beforeMatch.split('\n').length;
      const column = match.index - beforeMatch.lastIndexOf('\n');

      const issue: CodeIssue = {
        id: `${rule.id}-${lineNumber}-${column}`,
        ruleId: rule.id,
        title: rule.name,
        description: rule.message,
        severity: rule.severity === 'critical' ? 'error' : 
                 rule.severity === 'high' ? 'error' :
                 rule.severity === 'medium' ? 'warning' : 'info',
        location: {
          line: lineNumber,
          column,
          endLine: lineNumber,
          endColumn: column + match[0].length,
          file: 'input',
        },
        category: rule.category as CodeIssue['category'],
        suggestion: rule.suggestion,
        autoFixable: rule.autoFixable,
        references: rule.references,
        codeSnippet: match[0],
      };

      issues.push(issue);

      if (rule.category === 'security') {
        securityFindings.push({
          id: issue.id,
          type: rule.name,
          severity: rule.severity,
          vulnerability: rule.name,
          description: rule.message,
          location: { line: lineNumber, column, file: 'input' },
          cwe: rule.references.find(r => r.startsWith('CWE-')),
          owaspCategory: rule.references.find(r => r.includes('OWASP')),
          recommendation: rule.suggestion,
          references: rule.references,
        });
      }
    }
  }

  return { issues, securityFindings };
}
