/**
 * Swift/iOS Best Practices Detection System
 * Based on: Swift API Design Guidelines, Apple Human Interface Guidelines, SwiftUI Best Practices
 * Updated: 2024 Standards (iOS 17+, Swift 5.9+)
 */

import type { CodeIssue, SecurityFinding } from '../../types/analysis';

export interface SwiftDetectionRule {
  id: string;
  name: string;
  description: string;
  category: 'security' | 'performance' | 'best-practice' | 'style' | 'swiftui' | 'memory' | 'concurrency';
  severity: 'critical' | 'high' | 'medium' | 'low' | 'info';
  pattern: RegExp;
  message: string;
  suggestion: string;
  references: string[];
  autoFixable: boolean;
  fix?: (code: string, match: RegExpMatchArray) => string;
}

// Comprehensive Swift/iOS Detection Rules - Official Best Practices 2024
export const SWIFT_RULES: SwiftDetectionRule[] = [
  // ============ MEMORY MANAGEMENT RULES ============
  {
    id: 'SW-MEM001',
    name: 'Strong Reference Cycle',
    description: 'Detects potential retain cycles in closures',
    category: 'memory',
    severity: 'critical',
    pattern: /\{\s*(?!\[weak|unowned)[^}]*self\.\w+/g,
    message: 'Potential strong reference cycle. Closure captures self strongly.',
    suggestion: 'Use [weak self] or [unowned self] in closure capture list.',
    references: ['Swift Memory Management', 'ARC', 'Apple Memory Guidelines'],
    autoFixable: false,
  },
  {
    id: 'SW-MEM002',
    name: 'Force Unwrap',
    description: 'Detects force unwrap operator usage',
    category: 'memory',
    severity: 'high',
    pattern: /\w+!\./g,
    message: 'Force unwrapping (!) can cause runtime crashes.',
    suggestion: 'Use optional binding (if let/guard let), optional chaining (?.), or nil coalescing (??).',
    references: ['Swift Optionals', 'Safe Unwrapping'],
    autoFixable: false,
  },
  {
    id: 'SW-MEM003',
    name: 'Implicitly Unwrapped Optional',
    description: 'Detects implicitly unwrapped optional declarations',
    category: 'memory',
    severity: 'medium',
    pattern: /(?:var|let)\s+\w+\s*:\s*\w+!/g,
    message: 'Implicitly unwrapped optionals can cause crashes if accessed when nil.',
    suggestion: 'Use regular optionals (?) with proper unwrapping, or @IBOutlet for UI elements only.',
    references: ['Swift Optionals', 'IBOutlet Best Practices'],
    autoFixable: false,
  },
  {
    id: 'SW-MEM004',
    name: 'Delegate Without Weak',
    description: 'Detects delegate properties without weak reference',
    category: 'memory',
    severity: 'high',
    pattern: /var\s+\w*[Dd]elegate\s*:\s*(?!weak)/g,
    message: 'Delegate should be weak to prevent retain cycles.',
    suggestion: 'Declare as: weak var delegate: DelegateProtocol?',
    references: ['Swift Delegation Pattern', 'Memory Management'],
    autoFixable: false,
  },
  {
    id: 'SW-MEM005',
    name: 'Timer Without Invalidation',
    description: 'Detects Timer creation without proper lifecycle management',
    category: 'memory',
    severity: 'high',
    pattern: /Timer\.scheduledTimer\s*\([^)]*target:\s*self/g,
    message: 'Timer with target:self creates a strong reference. Must invalidate in deinit.',
    suggestion: 'Use Timer with block-based API with [weak self], or invalidate in deinit.',
    references: ['Timer Memory Management', 'iOS Lifecycle'],
    autoFixable: false,
  },
  {
    id: 'SW-MEM006',
    name: 'NotificationCenter Without Removal',
    description: 'Detects observer registration without removal',
    category: 'memory',
    severity: 'medium',
    pattern: /NotificationCenter\.default\.addObserver\s*\(/g,
    message: 'NotificationCenter observers should be removed when no longer needed.',
    suggestion: 'Remove observer in deinit, or use addObserver(forName:object:queue:using:) and store token.',
    references: ['NotificationCenter Best Practices', 'Memory Leaks'],
    autoFixable: false,
  },

  // ============ CONCURRENCY RULES (Swift Concurrency) ============
  {
    id: 'SW-CONC001',
    name: 'Main Actor Violation',
    description: 'Detects potential main thread violations',
    category: 'concurrency',
    severity: 'high',
    pattern: /Task\s*\{[^}]*(?:self\.tableView|self\.collectionView|UIApplication)/g,
    message: 'UI updates in Task may not be on main thread.',
    suggestion: 'Use @MainActor or Task { @MainActor in } for UI updates.',
    references: ['Swift Concurrency', 'MainActor', 'iOS Threading'],
    autoFixable: false,
  },
  {
    id: 'SW-CONC002',
    name: 'Async Without Await',
    description: 'Detects async functions not being awaited',
    category: 'concurrency',
    severity: 'medium',
    pattern: /Task\s*\{\s*[^}]*(?<!await\s)\w+\s*\(\s*\)[^}]*\}(?!.*await)/g,
    message: 'Async operation may not be awaited properly.',
    suggestion: 'Use await for async calls, or Task { await operation() }.',
    references: ['Swift Async/Await', 'Structured Concurrency'],
    autoFixable: false,
  },
  {
    id: 'SW-CONC003',
    name: 'DispatchQueue.main.sync',
    description: 'Detects dangerous main queue sync calls',
    category: 'concurrency',
    severity: 'critical',
    pattern: /DispatchQueue\.main\.sync\s*\{/g,
    message: 'DispatchQueue.main.sync can cause deadlock if called from main thread.',
    suggestion: 'Use DispatchQueue.main.async or check if already on main thread.',
    references: ['GCD Best Practices', 'Deadlock Prevention'],
    autoFixable: false,
  },
  {
    id: 'SW-CONC004',
    name: 'Data Race Risk',
    description: 'Detects potential data race conditions',
    category: 'concurrency',
    severity: 'high',
    pattern: /var\s+\w+\s*=[^}]*(?:DispatchQueue|Task|async)/g,
    message: 'Mutable state accessed from multiple threads may cause data races.',
    suggestion: 'Use actors, @MainActor, or synchronization mechanisms.',
    references: ['Swift Actors', 'Data Race Safety'],
    autoFixable: false,
  },
  {
    id: 'SW-CONC005',
    name: 'Sendable Conformance Missing',
    description: 'Detects types passed across concurrency boundaries',
    category: 'concurrency',
    severity: 'medium',
    pattern: /Task\s*\{[^}]*(?:class|struct)\s+\w+(?!.*Sendable)/g,
    message: 'Types passed across concurrency boundaries should conform to Sendable.',
    suggestion: 'Mark type as Sendable or use @unchecked Sendable with proper synchronization.',
    references: ['Sendable Protocol', 'Swift Concurrency'],
    autoFixable: false,
  },

  // ============ SWIFTUI RULES ============
  {
    id: 'SW-UI001',
    name: 'ObservableObject Without @Published',
    description: 'Detects ObservableObject with non-published properties',
    category: 'swiftui',
    severity: 'medium',
    pattern: /class\s+\w+\s*:\s*ObservableObject\s*\{[^}]*var\s+\w+(?!\s*:\s*(?:Published|@Published))/g,
    message: 'Properties in ObservableObject should use @Published for UI updates.',
    suggestion: 'Mark properties with @Published: @Published var property: Type',
    references: ['SwiftUI ObservableObject', 'State Management'],
    autoFixable: false,
  },
  {
    id: 'SW-UI002',
    name: 'State Outside View',
    description: 'Detects @State usage outside of View struct',
    category: 'swiftui',
    severity: 'high',
    pattern: /@State\s+(?:private\s+)?var\s+\w+(?![^}]*struct\s+\w+\s*:\s*View)/g,
    message: '@State should only be used inside View structs.',
    suggestion: 'Use @Published in ObservableObject, or @State only within View.',
    references: ['SwiftUI State', 'Property Wrappers'],
    autoFixable: false,
  },
  {
    id: 'SW-UI003',
    name: 'Heavy Computation in View Body',
    description: 'Detects expensive operations in View body',
    category: 'swiftui',
    severity: 'high',
    pattern: /var\s+body\s*:\s*some\s+View\s*\{[^}]*(?:\.filter|\.map|\.sorted|\.reduce)\s*\{/g,
    message: 'Collection operations in body run on every view update.',
    suggestion: 'Move computations to computed properties or use onAppear/task.',
    references: ['SwiftUI Performance', 'View Updates'],
    autoFixable: false,
  },
  {
    id: 'SW-UI004',
    name: 'Missing Identifiable',
    description: 'Detects ForEach without proper identification',
    category: 'swiftui',
    severity: 'medium',
    pattern: /ForEach\s*\([^)]*,\s*id:\s*\\\.self/g,
    message: 'Using \\.self as id can cause issues with duplicate values.',
    suggestion: 'Conform model to Identifiable and use ForEach(items) without explicit id.',
    references: ['SwiftUI ForEach', 'Identifiable Protocol'],
    autoFixable: false,
  },
  {
    id: 'SW-UI005',
    name: 'EnvironmentObject Without Providing',
    description: 'Detects @EnvironmentObject that may not be provided',
    category: 'swiftui',
    severity: 'high',
    pattern: /@EnvironmentObject\s+(?:private\s+)?var\s+\w+\s*:/g,
    message: '@EnvironmentObject will crash if not provided by ancestor view.',
    suggestion: 'Ensure .environmentObject() is called on ancestor view.',
    references: ['SwiftUI Environment', 'Dependency Injection'],
    autoFixable: false,
  },
  {
    id: 'SW-UI006',
    name: 'GeometryReader Overuse',
    description: 'Detects excessive GeometryReader usage',
    category: 'swiftui',
    severity: 'low',
    pattern: /GeometryReader\s*\{[^}]*GeometryReader/g,
    message: 'Nested GeometryReaders can cause layout issues and performance problems.',
    suggestion: 'Pass geometry values down to child views instead of nesting.',
    references: ['SwiftUI GeometryReader', 'Layout System'],
    autoFixable: false,
  },
  {
    id: 'SW-UI007',
    name: 'NavigationView Deprecated',
    description: 'Detects deprecated NavigationView usage',
    category: 'swiftui',
    severity: 'low',
    pattern: /NavigationView\s*\{/g,
    message: 'NavigationView is deprecated in iOS 16+.',
    suggestion: 'Use NavigationStack or NavigationSplitView for iOS 16+.',
    references: ['SwiftUI Navigation', 'iOS 16 Migration'],
    autoFixable: false,
  },

  // ============ BEST PRACTICE RULES ============
  {
    id: 'SW-BP001',
    name: 'Force Try',
    description: 'Detects force try usage',
    category: 'best-practice',
    severity: 'high',
    pattern: /try!\s+\w+/g,
    message: 'Force try (try!) will crash if the operation throws.',
    suggestion: 'Use do-catch block, try?, or handle errors properly.',
    references: ['Swift Error Handling', 'Try Best Practices'],
    autoFixable: false,
  },
  {
    id: 'SW-BP002',
    name: 'Force Cast',
    description: 'Detects force cast usage',
    category: 'best-practice',
    severity: 'high',
    pattern: /as!\s+\w+/g,
    message: 'Force cast (as!) will crash if the cast fails.',
    suggestion: 'Use conditional cast (as?) with optional binding.',
    references: ['Swift Type Casting', 'Safe Casting'],
    autoFixable: false,
  },
  {
    id: 'SW-BP003',
    name: 'Massive View Controller',
    description: 'Detects large UIViewController classes',
    category: 'best-practice',
    severity: 'medium',
    pattern: /class\s+\w+ViewController\s*:[^{]*\{(?:[^{}]*|\{[^{}]*\}){80,}/g,
    message: 'View Controller is too large. Consider splitting responsibilities.',
    suggestion: 'Use MVVM/Coordinator pattern. Extract logic to ViewModels.',
    references: ['iOS Architecture', 'MVVM Pattern', 'Clean Architecture'],
    autoFixable: false,
  },
  {
    id: 'SW-BP004',
    name: 'UserDefaults for Sensitive Data',
    description: 'Detects sensitive data in UserDefaults',
    category: 'security',
    severity: 'critical',
    pattern: /UserDefaults[^}]*(?:password|token|secret|key|credential|apiKey)/gi,
    message: 'Sensitive data should not be stored in UserDefaults.',
    suggestion: 'Use Keychain for sensitive data storage.',
    references: ['iOS Security', 'Keychain Services', 'OWASP Mobile'],
    autoFixable: false,
  },
  {
    id: 'SW-BP005',
    name: 'Print in Production',
    description: 'Detects print statements',
    category: 'best-practice',
    severity: 'low',
    pattern: /\bprint\s*\(/g,
    message: 'Print statements should be removed in production builds.',
    suggestion: 'Use os.log or a logging framework. Remove prints with #if DEBUG.',
    references: ['iOS Logging', 'Debug Best Practices'],
    autoFixable: false,
  },
  {
    id: 'SW-BP006',
    name: 'Magic Numbers',
    description: 'Detects hardcoded numbers',
    category: 'style',
    severity: 'info',
    pattern: /(?:\.frame\(|\.padding\(|\.font\()[^)]*\d{2,}/g,
    message: 'Avoid hardcoded numbers in UI. Use constants or design system.',
    suggestion: 'Define constants: static let padding: CGFloat = 16',
    references: ['Swift Style Guide', 'Design Systems'],
    autoFixable: false,
  },

  // ============ SECURITY RULES ============
  {
    id: 'SW-SEC001',
    name: 'Hardcoded API Key',
    description: 'Detects hardcoded API keys',
    category: 'security',
    severity: 'critical',
    pattern: /(?:apiKey|apiSecret|secretKey|accessToken)\s*[:=]\s*"[A-Za-z0-9_-]{16,}"/gi,
    message: 'Hardcoded API key detected. Keys can be extracted from app binary.',
    suggestion: 'Use secure storage, configuration files, or fetch from server at runtime.',
    references: ['iOS Security Best Practices', 'OWASP Mobile Top 10'],
    autoFixable: false,
  },
  {
    id: 'SW-SEC002',
    name: 'HTTP Instead of HTTPS',
    description: 'Detects insecure HTTP usage',
    category: 'security',
    severity: 'high',
    pattern: /URL\s*\(\s*string:\s*"http:\/\//g,
    message: 'Using HTTP instead of HTTPS exposes data to interception.',
    suggestion: 'Always use HTTPS for network requests.',
    references: ['App Transport Security', 'iOS Network Security'],
    autoFixable: true,
    fix: (code, match) => code.replace(/"http:\/\//, '"https://'),
  },
  {
    id: 'SW-SEC003',
    name: 'Disabled ATS',
    description: 'Detects App Transport Security exceptions',
    category: 'security',
    severity: 'high',
    pattern: /NSAllowsArbitraryLoads.*true|NSExceptionAllowsInsecureHTTPLoads.*true/g,
    message: 'App Transport Security is disabled. Network traffic may be insecure.',
    suggestion: 'Enable ATS. Only add specific domain exceptions if absolutely necessary.',
    references: ['App Transport Security', 'iOS Security Guide'],
    autoFixable: false,
  },
  {
    id: 'SW-SEC004',
    name: 'Jailbreak Detection Missing',
    description: 'Detects potential missing jailbreak checks',
    category: 'security',
    severity: 'medium',
    pattern: /KeychainAccess|Security\.framework|Keychain/g,
    message: 'Consider adding jailbreak detection for sensitive operations.',
    suggestion: 'Implement jailbreak detection for apps handling sensitive data.',
    references: ['iOS Security', 'Jailbreak Detection'],
    autoFixable: false,
  },
  {
    id: 'SW-SEC005',
    name: 'Biometric Without Fallback',
    description: 'Detects biometric auth without proper fallback',
    category: 'security',
    severity: 'medium',
    pattern: /LAContext\s*\(\s*\)\.canEvaluatePolicy\s*\([^)]*\)(?![^}]*fallback)/gi,
    message: 'Biometric authentication should have a secure fallback.',
    suggestion: 'Provide device passcode as fallback for biometric authentication.',
    references: ['LocalAuthentication', 'Biometric Best Practices'],
    autoFixable: false,
  },
  {
    id: 'SW-SEC006',
    name: 'SSL Pinning Missing',
    description: 'Detects URLSession without certificate pinning',
    category: 'security',
    severity: 'medium',
    pattern: /URLSession\s*\.\s*shared\s*\.\s*dataTask/g,
    message: 'Consider implementing SSL pinning for sensitive APIs.',
    suggestion: 'Use URLSessionDelegate with certificate pinning for sensitive requests.',
    references: ['SSL Pinning', 'Network Security'],
    autoFixable: false,
  },
  {
    id: 'SW-SEC007',
    name: 'Hardcoded String - Password',
    description: 'Detects hardcoded passwords in code',
    category: 'security',
    severity: 'critical',
    pattern: /(?:password|passwd|pwd)\s*[:=]\s*"[^"]+"/gi,
    message: 'CRITICAL: Hardcoded password detected. This is a severe security vulnerability.',
    suggestion: 'Never hardcode passwords. Use Keychain, secure environment variables, or prompt user.',
    references: ['OWASP Mobile Top 10', 'CWE-259', 'iOS Security Guide'],
    autoFixable: false,
  },
  {
    id: 'SW-SEC008',
    name: 'Hardcoded String - Secret',
    description: 'Detects hardcoded secrets in code',
    category: 'security',
    severity: 'critical',
    pattern: /(?:secret|token|bearer|auth)\s*[:=]\s*"[^"]{8,}"/gi,
    message: 'CRITICAL: Hardcoded secret/token detected. Can be extracted from compiled binary.',
    suggestion: 'Store secrets in Keychain or fetch securely from backend.',
    references: ['OWASP Mobile Top 10', 'CWE-798', 'iOS Security Guide'],
    autoFixable: false,
  },
  {
    id: 'SW-SEC009',
    name: 'Hardcoded String - Database URL',
    description: 'Detects hardcoded database connection strings',
    category: 'security',
    severity: 'critical',
    pattern: /(?:db|database|mongo|mysql|postgres|firebase)[A-Za-z]*(?:Url|URI|Connection)\s*[:=]\s*"[^"]+"/gi,
    message: 'CRITICAL: Hardcoded database URL detected. Database credentials exposed.',
    suggestion: 'Use secure configuration management. Never commit database URLs.',
    references: ['OWASP Mobile Top 10', 'CWE-798'],
    autoFixable: false,
  },
  {
    id: 'SW-SEC010',
    name: 'Hardcoded String - Private Key',
    description: 'Detects hardcoded private keys',
    category: 'security',
    severity: 'critical',
    pattern: /(?:privateKey|private_key|-----BEGIN\s+(?:RSA\s+)?PRIVATE\s+KEY-----)/gi,
    message: 'CRITICAL: Private key detected in code. Immediate security risk.',
    suggestion: 'Store private keys securely in Keychain. Never commit to source control.',
    references: ['OWASP Mobile Top 10', 'CWE-321'],
    autoFixable: false,
  },

  // ============ PERFORMANCE RULES ============
  {
    id: 'SW-PERF001',
    name: 'String Interpolation in Loop',
    description: 'Detects string interpolation in loops',
    category: 'performance',
    severity: 'low',
    pattern: /(?:for|while)\s+[^{]*\{[^}]*"[^"]*\\[^}]*\}/g,
    message: 'String interpolation in loop can be inefficient.',
    suggestion: 'Use String(format:) or append() for building strings in loops.',
    references: ['Swift String Performance'],
    autoFixable: false,
  },
  {
    id: 'SW-PERF002',
    name: 'Large Image Without Downsample',
    description: 'Detects UIImage loading without optimization',
    category: 'performance',
    severity: 'medium',
    pattern: /UIImage\s*\(\s*(?:named:|contentsOfFile:)/g,
    message: 'Loading large images directly can cause memory issues.',
    suggestion: 'Use ImageIO for downsampling large images before display.',
    references: ['iOS Image Best Practices', 'Memory Optimization'],
    autoFixable: false,
  },
  {
    id: 'SW-PERF003',
    name: 'Avoid objc Dynamic',
    description: 'Detects unnecessary @objc dynamic declarations',
    category: 'performance',
    severity: 'low',
    pattern: /@objc\s+dynamic\s+(?:var|func)/g,
    message: '@objc dynamic disables Swift optimizations.',
    suggestion: 'Only use @objc dynamic when KVO observation is required.',
    references: ['Swift Performance', 'Objective-C Interop'],
    autoFixable: false,
  },
  {
    id: 'SW-PERF004',
    name: 'CoreData Main Thread Fetch',
    description: 'Detects Core Data operations on main thread',
    category: 'performance',
    severity: 'high',
    pattern: /viewContext\.fetch\s*\(|viewContext\.save\s*\(/g,
    message: 'Heavy Core Data operations on viewContext block main thread.',
    suggestion: 'Use background context for heavy operations: container.performBackgroundTask',
    references: ['Core Data Concurrency', 'Performance'],
    autoFixable: false,
  },
];

/**
 * Run Swift/iOS-specific detection
 */
export function runSwiftDetection(code: string): { issues: CodeIssue[]; securityFindings: SecurityFinding[] } {
  const issues: CodeIssue[] = [];
  const securityFindings: SecurityFinding[] = [];

  for (const rule of SWIFT_RULES) {
    const regex = new RegExp(rule.pattern.source, rule.pattern.flags);
    let match;

    while ((match = regex.exec(code)) !== null) {
      const beforeMatch = code.substring(0, match.index);
      const lineNumber = beforeMatch.split('\n').length;
      const column = match.index - beforeMatch.lastIndexOf('\n');

      const issue: CodeIssue = {
        id: `${rule.id}-${lineNumber}-${column}`,
        ruleId: rule.id,
        title: rule.name,
        description: rule.message,
        severity: rule.severity === 'critical' ? 'error' : 
                 rule.severity === 'high' ? 'error' :
                 rule.severity === 'medium' ? 'warning' : 'info',
        location: {
          line: lineNumber,
          column,
          endLine: lineNumber,
          endColumn: column + match[0].length,
          file: 'input',
        },
        category: rule.category as any,
        suggestion: rule.suggestion,
        autoFixable: rule.autoFixable,
        references: rule.references,
        codeSnippet: match[0],
      };

      issues.push(issue);

      if (rule.category === 'security') {
        securityFindings.push({
          id: issue.id,
          type: rule.name,
          severity: rule.severity,
          vulnerability: rule.name,
          description: rule.message,
          location: { line: lineNumber, column, file: 'input' },
          cwe: rule.references.find(r => r.startsWith('CWE-')),
          owaspCategory: rule.references.find(r => r.includes('OWASP')),
          recommendation: rule.suggestion,
          references: rule.references,
        });
      }
    }
  }

  return { issues, securityFindings };
}

