
import { ArrowLeft, FileText, Shield, Scale, AlertCircle, Users, Code2 } from 'lucide-react';
import { useTheme } from '../../context/ThemeContext';
import { cn } from '../../utils/cn';

interface TermsOfServiceProps {
  onBack: () => void;
}

export function TermsOfService({ onBack }: TermsOfServiceProps) {
  const { isDark } = useTheme();
  console.log('TermsOfService Rendering, Mode:', isDark ? 'Dark' : 'Light');

  const sections = [
    {
      icon: FileText,
      title: '1. Acceptance of Terms',
      content: `By accessing and using CodeSentinel ("the Service"), you accept and agree to be bound by the terms and provisions of this agreement. If you do not agree to abide by these terms, please do not use this Service.

CodeSentinel is an AI-powered static code analysis platform designed to help developers identify security vulnerabilities, code quality issues, and optimization opportunities in their source code.`
    },
    {
      icon: Code2,
      title: '2. Description of Service',
      content: `CodeSentinel provides the following services:
• Static code analysis for 15+ programming languages
• Security vulnerability detection (OWASP Top 10)
• AI-powered code reviews and suggestions
• Control flow graph visualization
• Custom rule creation and management
• Code metrics and quality scoring
• Export functionality for analysis reports

The Service is provided "as is" and we reserve the right to modify, suspend, or discontinue any aspect of the Service at any time.`
    },
    {
      icon: Users,
      title: '3. User Accounts',
      content: `To access certain features of CodeSentinel, you must create an account through our authentication provider (Clerk). You are responsible for:
• Maintaining the confidentiality of your account credentials
• All activities that occur under your account
• Notifying us immediately of any unauthorized use
• Ensuring your account information is accurate and up-to-date

We reserve the right to terminate accounts that violate these terms or engage in abusive behavior.`
    },
    {
      icon: Shield,
      title: '4. Privacy and Data',
      content: `Your privacy is important to us. By using CodeSentinel:
• Code you submit for analysis is processed in real-time and not permanently stored on our servers
• Analysis results may be cached temporarily to improve performance
• We do not share your code or analysis results with third parties
• Authentication data is managed securely by Clerk
• AI analysis is performed using Groq's API with industry-standard security

For complete details, please review our Privacy Policy.`
    },
    {
      icon: Scale,
      title: '5. Acceptable Use',
      content: `You agree NOT to use CodeSentinel to:
• Upload malicious code intended to harm our systems or other users
• Attempt to reverse engineer, decompile, or extract our proprietary algorithms
• Use the Service for any illegal or unauthorized purpose
• Violate any laws in your jurisdiction
• Interfere with or disrupt the Service or servers
• Attempt to gain unauthorized access to any part of the Service
• Use automated systems to access the Service in a manner that exceeds reasonable use

We reserve the right to investigate and take appropriate action against anyone who violates these provisions.`
    },
    {
      icon: AlertCircle,
      title: '6. Intellectual Property',
      content: `CodeSentinel and its original content, features, and functionality are owned by the developers and are protected by international copyright, trademark, and other intellectual property laws.

Your code remains your property. By submitting code for analysis, you grant us a limited, non-exclusive license to process your code solely for the purpose of providing the analysis service.

The analysis results, suggestions, and reports generated by CodeSentinel are provided for informational purposes only.`
    },
    {
      icon: AlertCircle,
      title: '7. Disclaimer of Warranties',
      content: `THE SERVICE IS PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO:
• Warranties of merchantability
• Fitness for a particular purpose
• Non-infringement
• Accuracy or completeness of analysis results

CodeSentinel does not guarantee that:
• The Service will be uninterrupted or error-free
• All security vulnerabilities will be detected
• Analysis results are 100% accurate
• The Service will meet your specific requirements

You acknowledge that code analysis tools have limitations and should be used as part of a comprehensive security strategy, not as the sole means of ensuring code security.`
    },
    {
      icon: Scale,
      title: '8. Limitation of Liability',
      content: `IN NO EVENT SHALL CODESENTINEL, ITS DEVELOPERS, OR AFFILIATES BE LIABLE FOR ANY:
• Indirect, incidental, special, consequential, or punitive damages
• Loss of profits, data, use, goodwill, or other intangible losses
• Damages resulting from unauthorized access to your account
• Damages resulting from any bugs, viruses, or other harmful code
• Damages resulting from reliance on analysis results

This limitation applies regardless of the legal theory under which damages are sought.`
    },
    {
      icon: FileText,
      title: '9. Changes to Terms',
      content: `We reserve the right to modify these Terms of Service at any time. Changes will be effective immediately upon posting to the Service. Your continued use of CodeSentinel after any changes indicates your acceptance of the new terms.

We encourage you to review these terms periodically for any updates.`
    },
    {
      icon: Users,
      title: '10. Contact Information',
      content: `If you have any questions about these Terms of Service, please contact us:

• GitHub: github.com/Sharjeel-Saleem-06/CodeSentinel
• LinkedIn: linkedin.com/in/msharjeelsaleem

Last Updated: January 2026`
    }
  ];

  return (
    <div className={cn(
      "min-h-screen w-full relative",
      isDark
        ? "bg-slate-950 text-slate-200"
        : "bg-slate-50 text-slate-800"
    )}>
      <div className={cn(
        "absolute inset-0 z-0 pointer-events-none",
        isDark
          ? "bg-gradient-to-br from-slate-950 via-slate-900 to-indigo-950"
          : "bg-gradient-to-br from-slate-50 via-white to-purple-50"
      )} />

      {/* Header */}
      <header className={cn(
        "sticky top-0 z-50 backdrop-blur-xl border-b",
        isDark
          ? "bg-slate-900/80 border-slate-700/50"
          : "bg-white/80 border-gray-200"
      )}>
        <div className="max-w-4xl mx-auto px-6 py-4 flex items-center justify-between">
          <button
            onClick={onBack}
            className={cn(
              "flex items-center gap-2 px-4 py-2 rounded-xl font-medium transition-all",
              isDark
                ? "text-slate-300 hover:text-white hover:bg-slate-800"
                : "text-gray-600 hover:text-gray-900 hover:bg-gray-100"
            )}
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </button>

          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-purple-600 to-fuchsia-600 flex items-center justify-center shadow-lg">
              <Code2 className="w-5 h-5 text-white" />
            </div>
            <span className={cn(
              "font-bold text-lg",
              isDark ? "text-white" : "text-gray-900"
            )}>
              Code<span className="text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-fuchsia-400">Sentinel</span>
            </span>
          </div>
        </div>
      </header>

      {/* Content */}
      <main className="relative z-10 max-w-4xl mx-auto px-6 py-12">
        <div>
          {/* Title */}
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-16 h-16 rounded-2xl bg-gradient-to-br from-purple-600 to-fuchsia-600 mb-6 shadow-lg shadow-purple-500/30">
              <Scale className="w-8 h-8 text-white" />
            </div>
            <h1 className={cn(
              "text-4xl font-bold mb-4",
              isDark ? "text-white" : "text-gray-900"
            )}>
              Terms of Service
            </h1>
            <p className={cn(
              "text-lg",
              isDark ? "text-slate-400" : "text-gray-600"
            )}>
              Please read these terms carefully before using CodeSentinel
            </p>
          </div>

          {/* Sections */}
          <div className="space-y-8">
            {sections.map((section) => (
              <div
                key={section.title}
                className={cn(
                  "rounded-2xl border p-6 transition-all hover:shadow-lg",
                  isDark
                    ? "bg-slate-800/50 border-slate-700/50 hover:bg-slate-800/80"
                    : "bg-white border-gray-200 shadow-sm hover:shadow-md"
                )}
              >
                <div className="flex items-start gap-4">
                  <div className={cn(
                    "flex-shrink-0 w-10 h-10 rounded-xl flex items-center justify-center",
                    isDark ? "bg-purple-500/20" : "bg-purple-100"
                  )}>
                    <section.icon className="w-5 h-5 text-purple-600 dark:text-purple-400" />
                  </div>
                  <div className="flex-1">
                    <h2 className={cn(
                      "text-xl font-bold mb-3",
                      isDark ? "text-white" : "text-gray-900"
                    )}>
                      {section.title}
                    </h2>
                    <div className={cn(
                      "text-sm leading-relaxed whitespace-pre-line",
                      isDark ? "text-slate-300" : "text-gray-600"
                    )}>
                      {section.content}
                    </div>
                  </div>
                </div>
              </div>
            ))}
          </div>

          {/* Footer */}
          <div className={cn(
            "mt-12 text-center text-sm",
            isDark ? "text-slate-500" : "text-gray-500"
          )}>
            <p>© 2026 CodeSentinel. All rights reserved.</p>
            <p className="mt-2">
              Created by{' '}
              <a
                href="https://www.linkedin.com/in/msharjeelsaleem/"
                target="_blank"
                rel="noopener noreferrer"
                className="text-purple-500 hover:text-purple-400 font-medium"
              >
                Muhammad Sharjeel Saleem
              </a>
            </p>
          </div>
        </div>
      </main>
    </div>
  );
}

export default TermsOfService;
